USE [master]
GO
/****** Object:  Database [UserDataBase]    Script Date: 14.08.2022 12:23:28 ******/
CREATE DATABASE [UserDataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UserDataBase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UserDataBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UserDataBase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\UserDataBase_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [UserDataBase] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UserDataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UserDataBase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UserDataBase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UserDataBase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UserDataBase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UserDataBase] SET ARITHABORT OFF 
GO
ALTER DATABASE [UserDataBase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [UserDataBase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UserDataBase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UserDataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UserDataBase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UserDataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UserDataBase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UserDataBase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UserDataBase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UserDataBase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [UserDataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UserDataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UserDataBase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UserDataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UserDataBase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UserDataBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UserDataBase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UserDataBase] SET RECOVERY FULL 
GO
ALTER DATABASE [UserDataBase] SET  MULTI_USER 
GO
ALTER DATABASE [UserDataBase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UserDataBase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UserDataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UserDataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [UserDataBase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [UserDataBase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'UserDataBase', N'ON'
GO
ALTER DATABASE [UserDataBase] SET QUERY_STORE = OFF
GO
USE [UserDataBase]
GO
/****** Object:  Table [dbo].[ResultGame]    Script Date: 14.08.2022 12:23:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ResultGame](
	[UserId] [int] NOT NULL,
	[Scores] [int] NOT NULL,
 CONSTRAINT [PK_ResultGame_UserId] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserBonuses]    Script Date: 14.08.2022 12:23:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserBonuses](
	[UserId] [int] NOT NULL,
	[UserBonuses] [int] NULL,
 CONSTRAINT [PK_UserBonuses_UserId] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserInfo]    Script Date: 14.08.2022 12:23:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserInfo](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](1000) NOT NULL,
	[UserPassword] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_UserInfo_UserId] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserTheme]    Script Date: 14.08.2022 12:23:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserTheme](
	[UserId] [int] NOT NULL,
	[Red] [int] NULL,
	[Green] [int] NULL,
	[Blue] [int] NULL,
 CONSTRAINT [PK_UserTheme_UserId] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ResultGame]  WITH CHECK ADD  CONSTRAINT [FK_ResultGame_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[UserInfo] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ResultGame] CHECK CONSTRAINT [FK_ResultGame_UserId]
GO
ALTER TABLE [dbo].[UserBonuses]  WITH CHECK ADD  CONSTRAINT [FK_UserInfo_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[UserInfo] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserBonuses] CHECK CONSTRAINT [FK_UserInfo_UserId]
GO
ALTER TABLE [dbo].[UserTheme]  WITH CHECK ADD  CONSTRAINT [FK_UserTheme_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[UserInfo] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserTheme] CHECK CONSTRAINT [FK_UserTheme_UserId]
GO
USE [master]
GO
ALTER DATABASE [UserDataBase] SET  READ_WRITE 
GO
